<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<UserSecretsId>dotnet-TimeTrackerBot-24cc6dec-0a1e-457b-bc62-a6cadeb24dbf</UserSecretsId>
		<DisableWinExeOutputInference>false</DisableWinExeOutputInference>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="Microsoft.AspNetCore" Version="2.3.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
		<PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>
</Project>
